baseURL = 'https://bradmdav.github.io/'
languageCode = 'en-us'

theme = "hugo-theme-m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "https://www.youtube.com/channel/UChOeb9V5uoAcx9YsO-q5vjw"
    weight = 4


[params]
  author = "John Doe"
  description = "Thank you for finding Actively Engaged and welcome! The articles and videos you will find here cover a variety of topics in the areas of education, personal knowledge managent, executive functioning and technology. Click the link below find me at Medium.com"
  menu_item_separator = " • "
  
  [[params.social]]
    icon = "medium"
    name = "Medium"
    url = "https://medium.com/@DrBradDavis"

  [[params.social]]
    icon = "mail"
    name = "Mail"
    url = "mailto:drbmdav@gmail.com"

  
      

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
